from enum import Enum, auto

class Items(Enum):
    # Movement
    MORPH_BALL = auto()
    BOMBS = auto()
    BOOST_BALL = auto()
    SPIDER_BALL = auto()
    SPACE_BOOTS = auto()
    GRAPPLE_BEAM = auto()


    # Fighting
    MISSILES = auto()
    POWER_BOMB = auto()
    SUPER_MISSILE = auto()
    PLASMA_BEAM = auto()
    CHARGE_BEAM = auto()
    WAVE_BEAM = auto()
    ICE_BEAM = auto()

    FLAMETHROWER = auto()
    WAVEBUSTER = auto()
    ICE_SPREADER = auto()

    XRAY_VISOR = auto()
    THERMAL_VISOR = auto()

    VARIA_SUIT = auto()
    GRAVITY_SUIT = auto()

    MISSILE_EXPANSION = auto()
    ENERGY_TANK = auto()

    # Chozo
    ARTIFACT_LIFE = auto()
    ARTIFACT_WILD = auto()
    ARTIFACT_LIFEGIVER = auto()
    ARTIFACT_WORLD = auto()
    # Magmoor
    ARTIFACT_NATURE = auto()
    ARTIFACT_STRENGTH = auto()



class GameEvents(Enum):
    HIVE_MECHA_DEFEATED = auto()
    FLAAHGRA_DEFEATED = auto()
    INCINERATOR_DRONE_DEFEATED = auto()


class Locations(Enum):
    # --- Tallon Overworld ---
    # Landing Site / West
    TALLON_LANDING_SITE = auto()
    TALLON_CANYON_CAVERN = auto()
    TALLON_TALLON_CANYON = auto()
    TALLON_GULLY = auto()
    TALLON_ALCOVE = auto()
    TALLON_ROOT_TUNNEL = auto()
    TALLON_ROOT_CAVE = auto()
    TALLON_ARBOR_CHAMBER = auto()
    TALLON_TRANSPORT_TUNNEL_B = auto()
    TALLON_TRANSPORT_TO_MAGMOOR_CAVERNS_EAST = auto()
    TALLON_TRANSPORT_TUNNEL_A = auto()
    TALLON_TRANSPORT_TO_CHOZO_RUINS_WEST = auto()
    # Artifact temple
    TALLON_TEMPLE_HALL = auto()
    TALLON_TEMPLE_SECURITY_STATION = auto()
    TALLON_TEMPLE_LOBBY = auto()
    TALLON_ARTIFACT_TEMPLE = auto()
    # Frigate site
    TALLON_WATER_FALL_CAVERN = auto()
    TALLON_FRIGATE_CRASH_SITE = auto()
    TALLON_OVERGROWN_CAVERN = auto()
    TALLON_TRANSPORT_TUNNEL_C = auto()
    TALLON_TRANSPORT_TO_CHOZO_RUINS_EAST = auto()
    TALLON_FRIGATE_ACCESS_TUNNEL = auto()
    # Frigate
    TALLON_MAIN_VENTILATION_SHAFT_SECTION_C = auto()
    TALLON_MAIN_VENTILATION_SHAFT_SECTION_B = auto()
    TALLON_MAIN_VENTILATION_SHAFT_SECTION_A = auto()
    TALLON_REACTOR_CORE = auto()
    TALLON_REACTOR_ACCESS = auto()
    TALLON_SAVE_STATION = auto()
    TALLON_CARGO_FREIGHT_LIFE_TO_DECK_GAMMA = auto()
    TALLON_DECK_BETA_TRANSIT_HALL = auto()
    TALLON_BIOHAZARD_CONTAINMENT = auto()
    TALLON_DECK_BETA_SECURITY_HALL = auto()
    TALLON_BIOTECH_RESEARCH_AREA_1 = auto()
    TALLON_DECK_BETA_CONDUIT_HALL = auto()
    TALLON_CONNECTION_ELEVATOR_TO_DECK_BETA = auto()
    TALLON_HYDRO_ACCESS_TUNNEL = auto()
    # Great Tree
    TALLON_GREAT_TREE_HALL = auto()
    TALLON_TRANSPORT_TUNNEL_D = auto()
    TALLON_TRANSPORT_TO_CHOZO_RUINS_SOUTH = auto()
    TALLON_GREAT_TREE_CHAMBER = auto()
    TALLON_LIFE_GROVE_TUNNEL = auto()
    TALLON_TRANSPORT_TUNNEL_E = auto()
    TALLON_LIFE_GROVE = auto()
    TALLON_TRANSPORT_TO_PHAZON_MINES_EAST = auto()

    # --- Chozo Ruins ---
    # Nursery/Vault Loop
    CHOZO_TRANSPORT_TO_TALLON_OVERWORLD_NORTH = auto()
    CHOZO_RUINS_ENTRANCE = auto()
    CHOZO_MAIN_PLAZA_FLOOR = auto()
    CHOZO_MAIN_PLAZA_VAULT_LEDGE = auto()
    CHOZO_MAIN_PLAZA_GRAPPLE_LEDGE = auto()
    CHOZO_NURSERY_ACCESS = auto()
    CHOZO_EYON_TUNNEL = auto()
    CHOZO_RUINED_NURSERY = auto()
    CHOZO_SAVE_STATION_1 = auto()
    CHOZO_NORTH_ATRIUM = auto()
    CHOZO_RUINED_GALLERY = auto()
    CHOZO_CHOZO_MAP_STATION = auto()
    CHOZO_TOTEM_ACCESS = auto()
    CHOZO_HIVE_TOTEM = auto()
    CHOZO_TRANSPORT_ACCESS_NORTH = auto()
    CHOZO_TRANSPORT_TO_MAGMOOR_CAVERNS_NORTH = auto()
    CHOZO_VAULT_ACCESS = auto()
    CHOZO_VAULT = auto()
    CHOZO_PLAZA_ACCESS = auto()
    # Ruined Shrine/Tower of Light 
    CHOZO_RUINED_SHRINE_ACCESS = auto()
    CHOZO_RUINED_SHRINE = auto()
    CHOZO_TOWER_OF_LIGHT_ACCESS = auto()
    CHOZO_TOWER_OF_LIGHT = auto()
    CHOZO_TOWER_CHAMBER = auto()
    # Ruined Fountain / Training Chamber Loop
    CHOZO_RUINED_FOUNTAIN_ACCESS = auto()
    CHOZO_RUINED_FOUNTAIN = auto()
    CHOZO_MEDITATION_FOUNTAIN = auto()
    CHOZO_MAGMA_POOL_CLOSE_SIDE = auto()
    CHOZO_MAGMA_POOL_FAR_SIDE = auto()
    CHOZO_TRAINING_CHAMBER_ACCESS = auto()
    CHOZO_TRAINING_CHAMBER = auto()
    CHOZO_PISTON_TUNNEL = auto()
    # Sunchamber / Sun Tower
    CHOZO_ARBORETUM_ACCESS = auto()
    CHOZO_ARBORETUM = auto()
    CHOZO_SUNCHAMBER_LOBBY = auto()
    CHOZO_SUNCHAMBER_ACCESS = auto()
    CHOZO_SUNCHAMBER = auto()
    CHOZO_SUN_TOWER = auto()
    CHOZO_SUN_TOWER_ACCESS = auto()
    # Watery Hall / Dynamo
    CHOZO_GATHERING_HALL_ACCESS = auto()
    CHOZO_GATHERING_HALL_LOWER = auto()
    CHOZO_GATHERING_HALL_UPPER = auto()
    CHOZO_SAVE_STATION_2 = auto()
    CHOZO_WATERY_HALL_ACCESS = auto()
    CHOZO_WATERY_HALL = auto()
    CHOZO_DYNAMO_ACCESS = auto()
    CHOZO_DYNAMO = auto()
    # Energy Core / Burn Dome
    CHOZO_EAST_ATRIUM = auto()
    CHOZO_ENERGY_CORE_ACCESS = auto()
    CHOZO_ENERGY_CORE = auto()
    CHOZO_BURN_DOME_ACCESS = auto()
    CHOZO_BURN_DOME = auto()
    # Furnace / Hall of the Elders loop
    CHOZO_WEST_FURNACE_ACCESS = auto()
    CHOZO_FURNACE_ENTRANCE = auto()
    CHOZO_FURNACE_MAIN = auto()
    CHOZO_EAST_FURNACE_ACCESS = auto()
    CHOZO_CROSSWAY_ACCESS_WEST = auto()
    CHOZO_CROSSWAY = auto()
    CHOZO_CROSSWAY_ACCESS_SOUTH = auto()
    CHOZO_ELDER_HALL_ACCESS = auto()
    CHOZO_HALL_OF_THE_ELDERS = auto()
    CHOZO_ELDER_CHAMBER = auto()
    # Reflecting Pool / Transporters
    CHOZO_REFLECTING_POOL_ACCESS = auto()
    CHOZO_REFLECTING_POOL = auto()
    CHOZO_ANTECHAMBER = auto()
    CHOZO_SAVE_STATION_3 = auto()
    CHOZO_TRANSPORT_TO_TALLON_OVERWORLD_EAST = auto()
    CHOZO_TRANSPORT_ACCESS_SOUTH = auto()
    CHOZO_TRANSPORT_TO_TALLON_OVERWORLD_SOUTH = auto()

    # --- Magmoor Caverns ---
    # North to Monitor Station
    MAGMOOR_TRANSPORT_TO_CHOZO_RUINS_NORTH = auto()
    MAGMOOR_BURNING_TRAIL = auto()
    MAGMOOR_SAVE_STATION_MAGMOOR_A = auto()
    MAGMOOR_LAKE_TUNNEL = auto()
    MAGMOOR_LAVA_LAKE = auto()
    MAGMOOR_PIT_TUNNEL = auto()
    MAGMOOR_TRICLOPS_PIT = auto()
    MAGMOOR_STORAGE_CAVERN = auto()
    MAGMOOR_MONITOR_TUNNEL = auto()
    # Monitor Station
    MAGMOOR_MONITOR_STATION_LOWER = auto()
    MAGMOOR_MONITOR_STATION_UPPER = auto()  # After double jumping onto the very top part
    MAGMOOR_MONITOR_STATION_UPPER_LEDGE = auto()  # Across the bridge to warrior shrin
    MAGMOOR_TRANSPORT_TUNNEL_A = auto()
    MAGMOOR_TRANSPORT_TO_PHENDRANA_DRIFTS_NORTH = auto()
    MAGMOOR_WARRIOR_SHRINE = auto()
    MAGMOOR_SHORE_TUNNEL = auto()
    MAGMOOR_FIERY_SHORES = auto()
    MAGMOOR_TRANSPORT_TUNNEL_B = auto()
    MAGMOOR_TRANSPORT_TO_TALLON_OVERWORLD_WEST = auto()
    MAGMOOR_TWIN_FIRES_TUNNEL = auto()
    MAGMOOR_TWIN_FIRES = auto()
    MAGMOOR_PLASMA_PROCESSING = auto()
    # Wave Beam gated area
    MAGMOOR_NORTH_CORE_TUNNEL = auto()
    MAGMOOR_GEOTHERMAL_CORE = auto()
    MAGMOOR_SHORE_TUNNEL = auto()
    MAGMOOR_MAGMOOR_WORKSTATION = auto()
    MAGMOOR_TRANSPORT_TUNNEL_C = auto()
    MAGMOOR_TRANSPORT_TO_PHENDRANA_DRIFTS_SOUTH = auto()
    MAGMOOR_SAVE_STATION_MAGMOOR_B = auto()
    MAGMOOR_WORKSTATION_TUNNEL = auto()
    MAGMOOR_TRANSPORT_TO_PHAZON_MINES_WEST = auto()

    # --- Phendrana Drifts ---
    PHEN_TRANSPORT_TO_MAGMOOR_CAVERNS_WEST = auto()
    PHEN_SHORELINE_ENTRANCE = auto()
    PHEN_PHENDRANA_SHORELINES = auto()
    PHEN_TEMPLE_ENTRYWAY = auto()
    PHEN_CHOZO_ICE_TEMPLE = auto()
    PHEN_CHAPEL_TUNNEL = auto()
    PHEN_CHAPEL_OF_THE_ELDERS = auto()
    PHEN_ICE_RUINS_ACCESS = auto()
    PHEN_ICE_RUINS_EAST = auto()
    PHEN_PLAZA_WALKWAY = auto()
    PHEN_SAVE_STATION_B = auto()
    PHEN_RUINS_ENTRYWAY = auto()
    PHEN_ICE_RUINS_WEST = auto()
    PHEN_CANYON_ENTRYWAY = auto()
    PHEN_PHENDRANA_CANYON = auto()
    PHEN_COURTYARD_ENTRYWAY = auto()
    PHEN_RUINED_COURTYARD = auto()
    PHEN_SAVE_STATION_A = auto()
    # QUARANTINE AREA
    PHEN_QUARANTINE_ACCESS = auto()
    PHEN_NORTH_QUARANTINE_TUNNEL = auto()
    PHEN_QUARANTINE_CAVE = auto()
    PHEN_QUARANTINE_MONITOR = auto()
    PHEN_SOUTH_QUARANTINE_TUNNEL = auto()
    PHEN_TRANSPORT_TO_MAGMOOR_CAVERNS_SOUTH = auto()
    PHEN_TRANSPORT_ACCESS = auto()
    PHEN_FROZEN_PIKE = auto()
    PHEN_PIKE_ACCESS = auto()
    # Research Lab Aether / Tower
    PHEN_RESEARCH_CORE = auto()
    PHEN_RESEARCH_CORE_ACCESS = auto()
    PHEN_RESEARCH_LAB_AETHER = auto()
    PHEN_AETHER_LAB_ENTRYWAY = auto()
    PHEN_EAST_TOWER = auto()
    PHEN_CONTROL_TOWER = auto()
    PHEN_WEST_TOWER = auto()
    PHEN_WEST_TOWER_ENTRANCE = auto()
    # Research lab Hydra / Observatory
    PHEN_SPECIMEN_STORAGE = auto()
    PHEN_RESEARCH_ENTRANCE = auto()
    PHEN_MAP_STATION = auto()
    PHEN_HYDRA_LAB_ENTRYWAY = auto()
    PHEN_RESEARCH_LAB_HYDRA = auto()
    PHEN_OBSERVATORY_ACCESS = auto()
    PHEN_OBSERVATORY = auto()
    PHEN_SAVE_STATION_D = auto()
    # Frost Cave / Edge
    PHEN_FROST_CAVE_ACCESS = auto()
    PHEN_FROST_CAVE = auto()
    PHEN_SAVE_STATION_C = auto()
    PHEN_UPPER_EDGE_TUNNEL = auto()
    PHEN_PHENDRANAS_EDGE = auto()
    PHEN_STORAGE_CAVE = auto()
    PHEN_SECURITY_CAVE = auto()
    # Gravity Chamber
    PHEN_HUNTER_CAVE_ACCESS = auto()
    PHEN_HUNTER_CAVE = auto()
    PHEN_LOWER_EDGE_TUNNEL = auto()
    PHEN_CHAMBER_ACCESS = auto()
    PHEN_GRAVITY_CHAMBER = auto()
    PHEN_LAKE_TUNNEL = auto()

